version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  #aws-ecs: circleci/aws-ecs@0x.y.z  ecsにもアップする場合の処理

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
    
