version: '2.1'

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          #context: myContext
          #create-repo: true                # trueの場合は新規でECRレポジトリを作成するので、repoパラメータには現在ECRにないリポジトリ名を指定する。すでにあり作成いらないなら、ここはfalseにする
          dockerfile: myDockerfile
          no-output-timeout: 20m
          #path: pathToMyDockerfile
          path: pathToMyDockerfile
          profile-name: myProfileName
          region: AWS_DEFAULT_REGION
          repo: AWS_RESOURCE_NAME_PREFIX
          skip-when-tags-exist: false
          #tag: 'latest,myECRRepoTag'        # 小文字でないとダメ。英語入れるなら。'名前:タグ' 形式で名前とオプションのタグを指定
          tag: 'latest,1.0'                 

